### PR TITLE
Fix compilation for the latest nightly

### PR DESCRIPTION
**Pull request by fbecart**
These minimalistic commits make the compilation possible (`src` and `tests`) using the latest nightly build of Rust.

I'm super new to Rust, and some of the fixes might not be the ideal solution.

### CODE REVIEW

**Comment by neich** [comment]
It looks ok to me.

And don't worry, I'am also very new to Rust ... ;-)

**Comment by fbecart** [comment]
Thanks for the review. I'll keep playing with the project, see if I can contribute in a positive manner :)

**Comment by neich** [comment]
I'm having trouble to compile the code with the beta version of the compiler. Specifically, #!feature() is forbidden, so the code needs a deep review. I'm on it. I want to depart from nighties now that there is a beta version.

**Comment by neich** [comment]
Also, I need a clear way to deal with strings. Rust has been changing a lot in this regard, and it's still not clear to me how to do it. I have found this interesting discussion:

http://users.rust-lang.org/t/ergonomics-of-creating-string-s/850

**Comment by fbecart** [comment]
I ran in the same issue when using the beta release, and that's the reason why I sticked to the nightly. But making the lib beta-compatible would be a very nice improvement :)

Regarding strings, I wasn't aware of the whole discussion. Thanks for the link :)

I'm currently trying to make the integration tests pass in my environment.

**Comment by neich** [comment]
I have merged your changes ... and some more to make rust-cql to compile with rust beta. There is still a lot to do, but at least now we have a stable language.

**Comment by fbecart** [comment]
Wow, I wasn't expecting a merge anymore. I feel grateful for you to accept my commits. Thanks!

**Pull request merged**
